language: node_js

sudo: false

branches:
  only:
    - master
    - dev

node_js:
  - "5"

install:
   # Disable the spinner, it looks bad on Travis
  - npm config set spin false
  - npm install



after_success:

    # deploy demo
    - test $TRAVIS_BRANCH = "master" && ./script/deploy-gh-pages.sh

    # push to release branch
    - test $TRAVIS_BRANCH = "master" && ./script/release.sh
