language: node_js

sudo: false

branches:
  only:
    - master

node_js:
  - "5"

install:
   # Disable the spinner, it looks bad on Travis
  - npm config set spin false
  - npm install


script:
    # test
    - npm test


    # build demo
    - rm -r -f ./dist; webpack

    # deploy demo to gh pages
    - cd ./dist
    - git init
    - git config user.name "Travis CI"
    - git config user.email "me@platane.me"
    - git add .
    - git commit -m "Deploy to GitHub Pages"
    - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1
    - cd ..


    # build bundle
    - rm -r -f ./dist; npm run bundle

    # deploy demo to gh pages
    - cp package.json ./dist/package.json
    - cd ./dist
    - git init
    - git config user.name "Travis CI"
    - git config user.email "me@platane.me"
    - git add .
    - git commit -m "Release"
    - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:release > /dev/null 2>&1
    - cd ..
